plugins {
    id 'java-library'
}

dependencies {
    implementation project(':server-java:application')
    implementation 'org.springframework.boot:spring-boot-starter-security'
    implementation 'org.springframework.boot:spring-boot-starter-oauth2-resource-server'
    implementation 'com.fasterxml.jackson.core:jackson-databind'
    implementation 'org.springframework:spring-web'
    compileOnly 'jakarta.servlet:jakarta.servlet-api'

    testImplementation 'jakarta.servlet:jakarta.servlet-api'
    testImplementation 'org.springframework.boot:spring-boot-starter-test'
    testImplementation 'org.springframework.security:spring-security-test'
    testRuntimeOnly 'org.junit.platform:junit-platform-launcher'
}
