plugins {
    id 'java-library'
}

dependencies {
    implementation platform("${smartDomainGroup}:smart-domain-bom:${smartDomainVersion}")
    implementation "${smartDomainGroup}:smart-domain-mybatis"
    implementation "${smartDomainGroup}:smart-domain-mybatis-spring-boot-starter"
    implementation project(':server-java:application')
    implementation project(':server-java:domain')
    implementation 'com.fasterxml.jackson.core:jackson-databind'
    implementation 'com.fasterxml.jackson.dataformat:jackson-dataformat-yaml'
    implementation 'com.zaxxer:HikariCP'
    implementation 'jakarta.inject:jakarta.inject-api'
    implementation 'org.mybatis.spring.boot:mybatis-spring-boot-starter:3.0.4'
    implementation 'org.springframework:spring-jdbc'
    implementation 'org.flywaydb:flyway-core'
    implementation 'org.flywaydb:flyway-database-postgresql'
    runtimeOnly 'org.postgresql:postgresql'

    testImplementation 'org.springframework.boot:spring-boot-starter-test'
    testImplementation 'org.testcontainers:junit-jupiter'
    testImplementation 'org.testcontainers:postgresql'
    testRuntimeOnly 'org.junit.platform:junit-platform-launcher'
}
