package reengineering.ddd.evidence.persistent.mappers;

import java.time.Instant;

public final class ExecutionRows {
  private ExecutionRows() {}

  public record PairRunRow(
      String id,
      String reference,
      String workspaceId,
      String iterationId,
      String storyId,
      String storyRevisionId,
      String storyRevisionSha256,
      String approvedTaskingPlanId,
      String approvedTaskingPlanSha256,
      String baseCommitSha,
      String branchName,
      String status,
      String checkpoint,
      int version,
      String cursor,
      String completedTestIds,
      String completedStepKeys,
      String executionBudget,
      String budgetUsage,
      String leaseOwnerId,
      String leaseTokenSha256,
      Instant leaseExpiresAt,
      String currentDiffSha256,
      String finalManifestSha256,
      String approvedCommitSha,
      Instant startedAt,
      Instant updatedAt,
      Instant completedAt) {}

  public record PairDriverAttemptRow(
      String id,
      String pairRunId,
      String actionId,
      int sequence,
      String role,
      String mode,
      String taskId,
      String testId,
      String processId,
      String stepId,
      String summary,
      String changedPaths,
      String beforeWorktreeSha256,
      String afterWorktreeSha256,
      String diffSha256,
      int agentCallCount,
      Integer inputTokens,
      Integer outputTokens,
      Instant completedAt,
      String recordSha256) {}

  public record PairCommandObservationRow(
      String id,
      String pairRunId,
      String actionId,
      int sequence,
      String stage,
      String taskId,
      String testId,
      String processId,
      String stepId,
      String command,
      String termination,
      Integer exitCode,
      String signal,
      int durationMs,
      String stdoutSha256,
      int stdoutBytes,
      int stdoutLines,
      String stderrSha256,
      int stderrBytes,
      int stderrLines,
      String worktreeSha256,
      String diffSha256,
      String failureFingerprint,
      Instant observedAt,
      String previousRecordSha256,
      String recordSha256) {}

  public record PairRedReviewRow(
      String id,
      String pairRunId,
      String actionId,
      String observationId,
      String classification,
      boolean accepted,
      String reason,
      Instant reviewedAt,
      String recordSha256) {}

  public record PairExceptionRow(
      String id,
      String pairRunId,
      String actionId,
      String kind,
      String summary,
      String failureFingerprint,
      String allowedRoutes,
      Instant raisedAt,
      Instant resolvedAt,
      String recordSha256) {}

  public record PairManifestRow(
      String id,
      String pairRunId,
      String approvedTaskingPlanSha256,
      String storyRevisionSha256,
      String baseCommitSha,
      String completedTestIds,
      String completedStepKeys,
      String driverAttemptIds,
      String commandObservationIds,
      String redReviewIds,
      String changedPaths,
      String finalDiffSha256,
      String evidenceChainSha256,
      Instant generatedAt,
      String contentSha256) {}

  public record PairDecisionRow(
      String id,
      String pairRunId,
      int sequence,
      String action,
      String reason,
      String manifestSha256,
      String diffSha256,
      String commitSha,
      String decidedByUserId,
      Instant decidedAt,
      String contentSha256) {}

  public record ShowcaseRunRow(
      String id,
      String reference,
      int attempt,
      String workspaceId,
      String iterationId,
      String storyId,
      String storyRevisionId,
      String storyRevisionSha256,
      String approvedTaskingPlanId,
      String approvedTaskingPlanSha256,
      String pairRunId,
      String pairManifestId,
      String pairManifestSha256,
      String approvedCommitSha,
      String stage,
      int version,
      String evidenceBundleSha256,
      Instant startedAt,
      Instant updatedAt,
      Instant completedAt) {}

  public record ShowcaseQ2Row(
      String id,
      String showcaseRunId,
      String actionId,
      int sequence,
      String testId,
      String scenarioIds,
      String processId,
      String stepId,
      String projectId,
      String command,
      String termination,
      Integer exitCode,
      String signal,
      int durationMs,
      String stdoutSha256,
      int stdoutBytes,
      int stdoutLines,
      String stderrSha256,
      int stderrBytes,
      int stderrLines,
      String approvedCommitSha,
      String worktreeSha256,
      Instant observedAt,
      String previousRecordSha256,
      String recordSha256) {}

  public record ShowcaseProductRow(
      String id,
      String showcaseRunId,
      String scenarioId,
      String scenarioReference,
      String givenSteps,
      String whenStep,
      String expectedThenSteps,
      String businessData,
      String observedOutcomes,
      String observation,
      String valueFeedback,
      String evidenceRefs,
      String observedByUserId,
      Instant observedAt,
      String contentSha256) {}

  public record ShowcaseRiskRow(
      String id,
      String showcaseRunId,
      String quadrant,
      String disposition,
      String activities,
      String reason,
      String decidedByUserId,
      Instant decidedAt,
      String contentSha256) {}

  public record ShowcaseEvaluationRow(
      String id,
      String showcaseRunId,
      int sequence,
      String quadrant,
      String activity,
      String outcome,
      String finding,
      String evidenceRefs,
      String observedByUserId,
      Instant observedAt,
      String contentSha256) {}

  public record ShowcaseReviewRow(
      String id,
      String showcaseRunId,
      String evidenceBundleSha256,
      String observedFacts,
      String productDomainFeedback,
      String technicalQualityFeedback,
      String unresolvedAssumptions,
      String recommendation,
      Instant reviewedAt,
      String contentSha256) {}

  public record ShowcaseDecisionRow(
      String id,
      String showcaseRunId,
      String action,
      String reason,
      String feedbackTarget,
      String evidenceBundleSha256,
      String reviewId,
      String decidedByUserId,
      Instant decidedAt,
      String contentSha256) {}

  public record RespondCandidateRow(
      String id,
      String reference,
      int sequence,
      String actionId,
      String workspaceId,
      String iterationId,
      String storyId,
      String storyRevisionId,
      String showcaseRunId,
      String showcaseDecisionId,
      String authority,
      String authoritySha256,
      String promotions,
      String noPromotionReason,
      String observedOutcomes,
      String residualRisks,
      String nextProbe,
      Instant proposedAt,
      String contentSha256) {}

  public record RespondDecisionRow(
      String id,
      String candidateId,
      String action,
      String reason,
      String candidateSha256,
      String authoritySha256,
      String decidedByUserId,
      Instant decidedAt,
      String contentSha256) {}
}
