/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  '/api': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations['get_root'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/health': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations['get_health'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/users/{userId}': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations['get_user'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/users/{userId}/sidebar': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations['get_user_sidebar'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/users/{userId}/workspaces': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations['list_workspaces'];
    put?: never;
    post: operations['create_workspace'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/users/{userId}/workspaces/{workspaceId}': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations['get_workspace'];
    put: operations['update_workspace'];
    post?: never;
    delete: operations['delete_workspace'];
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/users/{userId}/workspaces/{workspaceId}/members': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations['list_workspace_members'];
    put?: never;
    post: operations['add_workspace_member'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/users/{userId}/workspaces/{workspaceId}/members/{memberId}': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations['get_workspace_member'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/workspaces/{workspaceId}/diagrams': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations['list_diagrams'];
    put?: never;
    post: operations['create_diagram'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/workspaces/{workspaceId}/diagrams/{diagramId}': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations['get_diagram'];
    put: operations['update_diagram'];
    post?: never;
    delete: operations['delete_diagram'];
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/workspaces/{workspaceId}/diagrams/{diagramId}/nodes': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations['list_diagram_nodes'];
    put?: never;
    post: operations['create_diagram_node'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/workspaces/{workspaceId}/diagrams/{diagramId}/nodes/{nodeId}': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations['get_diagram_node'];
    put: operations['update_diagram_node'];
    post?: never;
    delete: operations['delete_diagram_node'];
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/workspaces/{workspaceId}/diagrams/{diagramId}/edges': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations['list_diagram_edges'];
    put?: never;
    post: operations['create_diagram_edge'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/workspaces/{workspaceId}/diagrams/{diagramId}/edges/{edgeId}': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations['get_diagram_edge'];
    put: operations['update_diagram_edge'];
    post?: never;
    delete: operations['delete_diagram_edge'];
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/workspaces/{workspaceId}/diagrams/{diagramId}/versions': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations['list_diagram_versions'];
    put?: never;
    post: operations['create_diagram_version'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/workspaces/{workspaceId}/diagrams/{diagramId}/commit-draft': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations['get_diagram_for_commit_draft'];
    put?: never;
    post: operations['commit_diagram_draft'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/workspaces/{workspaceId}/diagrams/{diagramId}/publish': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations['get_diagram_for_publish'];
    put?: never;
    post: operations['publish_diagram'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/workspaces/{workspaceId}/diagrams/{diagramId}/propose-model': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations['get_diagram_for_propose_model'];
    put?: never;
    post: operations['propose_diagram_model'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/workspaces/{workspaceId}/logical-entities': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations['list_logical_entities'];
    put?: never;
    post: operations['create_logical_entity'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/workspaces/{workspaceId}/logical-entities/{entityId}': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations['get_logical_entity'];
    put: operations['update_logical_entity'];
    post?: never;
    delete: operations['delete_logical_entity'];
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
}
export type webhooks = Record<string, never>;
export interface components {
  schemas: {
    AddMemberInput: {
      role?: string | null;
      user: components['schemas']['RefModel'];
    };
    BTreeMap: {
      [key: string]: {
        href: string;
      };
    };
    CommitDraftInput: {
      edges?: components['schemas']['EdgeInput'][] | null;
      nodes?: components['schemas']['NodeInput'][] | null;
    };
    CommitResult: {
      committed: boolean;
    };
    CreateDiagramInput: {
      title: string;
      type?: null | components['schemas']['DiagramType'];
    };
    CreateLogicalEntityInput: {
      attributes: components['schemas']['EntityAttribute'][];
      description?: string | null;
      label?: string | null;
      name: string;
      subType?: string | null;
      type: components['schemas']['LogicalEntityType'];
    };
    DeletedResult: {
      deleted: boolean;
    };
    DiagramCollectionEmbedded: {
      diagrams: components['schemas']['DiagramResource'][];
    };
    DiagramCollectionResource: {
      _embedded: components['schemas']['DiagramCollectionEmbedded'];
      _links: components['schemas']['BTreeMap'];
      _templates: components['schemas']['BTreeMap'];
      page: components['schemas']['PageModel'];
    };
    DiagramResource: {
      _links: components['schemas']['BTreeMap'];
      _templates: components['schemas']['BTreeMap'];
      createdAt: string;
      id: string;
      status: components['schemas']['DiagramStatus'];
      title: string;
      type: components['schemas']['DiagramType'];
      updatedAt: string;
      viewport: components['schemas']['Viewport'];
    };
    DiagramSnapshot: {
      edges: components['schemas']['SnapshotEdge'][];
      nodes: components['schemas']['SnapshotNode'][];
      viewport: components['schemas']['Viewport'];
    };
    /** @enum {string} */
    DiagramStatus: 'draft' | 'published';
    /** @enum {string} */
    DiagramType:
      | 'flowchart'
      | 'sequence'
      | 'class'
      | 'component'
      | 'state'
      | 'activity'
      | 'fulfillment';
    DiagramVersionCollectionEmbedded: {
      versions: components['schemas']['DiagramVersionResource'][];
    };
    DiagramVersionCollectionResource: {
      _embedded: components['schemas']['DiagramVersionCollectionEmbedded'];
      _links: components['schemas']['BTreeMap'];
    };
    DiagramVersionResource: {
      _links: components['schemas']['BTreeMap'];
      createdAt: string;
      id: string;
      name: string;
      snapshot: components['schemas']['DiagramSnapshot'];
    };
    EdgeCollectionEmbedded: {
      edges: components['schemas']['EdgeResource'][];
    };
    EdgeCollectionResource: {
      _embedded: components['schemas']['EdgeCollectionEmbedded'];
      _links: components['schemas']['BTreeMap'];
    };
    EdgeInput: {
      animated?: boolean | null;
      data?: {
        [key: string]: unknown;
      } | null;
      hidden?: boolean | null;
      id?: string | null;
      /** Format: double */
      interactionWidth?: number | null;
      kind?: string | null;
      label?: string | null;
      markerEnd?: {
        [key: string]: unknown;
      } | null;
      markerStart?: {
        [key: string]: unknown;
      } | null;
      pathOptions?: {
        [key: string]: unknown;
      } | null;
      relationType?: string | null;
      source: components['schemas']['RefModel'];
      sourceHandle?: string | null;
      style?: {
        [key: string]: unknown;
      } | null;
      target: components['schemas']['RefModel'];
      targetHandle?: string | null;
    };
    EdgeResource: {
      _links: components['schemas']['BTreeMap'];
      animated: boolean;
      createdAt: string;
      data: {
        [key: string]: unknown;
      };
      hidden: boolean;
      id: string;
      /** Format: double */
      interactionWidth?: number | null;
      kind?: string | null;
      label?: string | null;
      markerEnd?: {
        [key: string]: unknown;
      } | null;
      markerStart?: {
        [key: string]: unknown;
      } | null;
      pathOptions: {
        [key: string]: unknown;
      };
      relationType?: string | null;
      source: components['schemas']['RefModel'];
      sourceHandle?: string | null;
      style: {
        [key: string]: unknown;
      };
      target: components['schemas']['RefModel'];
      targetHandle?: string | null;
      updatedAt: string;
    };
    EntityAttribute: {
      description?: string | null;
      id: string;
      label?: string | null;
      name: string;
      type?: string | null;
    };
    ErrorBody: {
      error: string;
    };
    HealthResource: {
      _links: components['schemas']['BTreeMap'];
      service: string;
      status: string;
    };
    Link: {
      href: string;
    };
    LinkedRefModel: {
      _links: components['schemas']['BTreeMap'];
      id: string;
    };
    LogicalEntityCollectionEmbedded: {
      logicalEntities: components['schemas']['LogicalEntityResource'][];
    };
    LogicalEntityCollectionResource: {
      _embedded: components['schemas']['LogicalEntityCollectionEmbedded'];
      _links: components['schemas']['BTreeMap'];
      page: components['schemas']['PageModel'];
    };
    LogicalEntityResource: {
      _links: components['schemas']['BTreeMap'];
      attributes: components['schemas']['EntityAttribute'][];
      createdAt: string;
      description?: string | null;
      id: string;
      label?: string | null;
      name: string;
      subType?: string | null;
      type: components['schemas']['LogicalEntityType'];
      updatedAt: string;
    };
    /** @enum {string} */
    LogicalEntityType: 'EVIDENCE' | 'PARTICIPANT' | 'ROLE' | 'CONTEXT';
    MemberCollectionEmbedded: {
      members: components['schemas']['MemberResource'][];
    };
    MemberCollectionResource: {
      _embedded: components['schemas']['MemberCollectionEmbedded'];
      _links: components['schemas']['BTreeMap'];
      total: number;
    };
    MemberResource: {
      _links: components['schemas']['BTreeMap'];
      createdAt: string;
      id: string;
      role: string;
      updatedAt: string;
      user: components['schemas']['LinkedRefModel'];
      workspace: components['schemas']['LinkedRefModel'];
    };
    NodeCollectionEmbedded: {
      nodes: components['schemas']['NodeResource'][];
    };
    NodeCollectionResource: {
      _embedded: components['schemas']['NodeCollectionEmbedded'];
      _links: components['schemas']['BTreeMap'];
    };
    NodeEmbedded: {
      'logical-entity': components['schemas']['LogicalEntityResource'];
    };
    NodeInput: {
      data?: {
        [key: string]: unknown;
      } | null;
      /** Format: int64 */
      height?: number | null;
      id?: string | null;
      kind: string;
      logicalEntity?: null | components['schemas']['RefModel'];
      parent?: null | components['schemas']['RefModel'];
      position?: null | components['schemas']['Position'];
      /** Format: int64 */
      width?: number | null;
    };
    NodeResource: {
      _embedded?: null | components['schemas']['NodeEmbedded'];
      _links: components['schemas']['BTreeMap'];
      createdAt: string;
      data: {
        [key: string]: unknown;
      };
      /** Format: int64 */
      height?: number | null;
      id: string;
      kind: string;
      parent?: null | components['schemas']['RefModel'];
      position: components['schemas']['Position'];
      updatedAt: string;
      /** Format: int64 */
      width?: number | null;
    };
    PageModel: {
      /** Format: int32 */
      number: number;
      /** Format: int32 */
      size: number;
      /** Format: int64 */
      totalElements: number;
      /** Format: int64 */
      totalPages: number;
    };
    Position: {
      /** Format: double */
      x: number;
      /** Format: double */
      y: number;
    };
    ProposeModelInput: {
      requirement: string;
    };
    PublishResult: {
      published: boolean;
    };
    RefModel: {
      id: string;
    };
    RootResource: {
      _links: components['schemas']['BTreeMap'];
    };
    SidebarItem: {
      active?: boolean | null;
      defaultOpen?: boolean | null;
      href: string;
      icon: string;
      key: string;
      label: string;
      path: string;
      rel?: string | null;
      template?: string | null;
      type: string;
    };
    SidebarResource: {
      _links: components['schemas']['BTreeMap'];
      sections: components['schemas']['SidebarSection'][];
    };
    SidebarSection: {
      defaultOpen: boolean;
      items: components['schemas']['SidebarItem'][];
      key: string;
      title: string;
    };
    SnapshotEdge: {
      description: components['schemas']['EdgeInput'];
      id?: string | null;
    };
    SnapshotNode: {
      description: components['schemas']['NodeInput'];
      id: string;
    };
    TemplateProperty: {
      /** Format: int32 */
      minLength?: number | null;
      name: string;
      prompt?: string | null;
      required?: boolean | null;
      type?: string | null;
      value?: string | null;
    };
    UpdateDiagramInput: {
      status?: null | components['schemas']['DiagramStatus'];
      title?: string | null;
      type?: null | components['schemas']['DiagramType'];
      viewport?: null | components['schemas']['Viewport'];
      /** Format: double */
      'viewport.x'?: number | null;
      /** Format: double */
      'viewport.y'?: number | null;
      /** Format: double */
      'viewport.zoom'?: number | null;
    };
    UpdateLogicalEntityInput: {
      attributes?: components['schemas']['EntityAttribute'][] | null;
      description?: string | null;
      label?: string | null;
      name?: string | null;
      subType?: string | null;
      type?: null | components['schemas']['LogicalEntityType'];
    };
    UserResource: {
      _links: components['schemas']['BTreeMap'];
      email?: string | null;
      id: string;
      name: string;
    };
    Viewport: {
      /** Format: double */
      x: number;
      /** Format: double */
      y: number;
      /** Format: double */
      zoom: number;
    };
    WorkspaceCollectionEmbedded: {
      workspaces: components['schemas']['WorkspaceResource'][];
    };
    WorkspaceCollectionResource: {
      _embedded: components['schemas']['WorkspaceCollectionEmbedded'];
      _links: components['schemas']['BTreeMap'];
      page: components['schemas']['PageModel'];
    };
    WorkspaceInput: {
      description?: string | null;
      metadata?: {
        [key: string]: string;
      } | null;
      status?: string | null;
      title: string;
    };
    WorkspaceResource: {
      _links: components['schemas']['BTreeMap'];
      createdAt: string;
      description?: string | null;
      id: string;
      metadata: {
        [key: string]: string;
      };
      status: string;
      title: string;
      updatedAt: string;
    };
  };
  responses: never;
  parameters: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
  get_root: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description API root resource */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/vnd.evidence.root+json': components['schemas']['RootResource'];
        };
      };
    };
  };
  get_health: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Health resource */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/vnd.evidence.health+json': components['schemas']['HealthResource'];
        };
      };
    };
  };
  get_user: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        /** @description User id */
        userId: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description User resource */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/vnd.evidence.user+json': components['schemas']['UserResource'];
        };
      };
      /** @description Validation error */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorBody'];
        };
      };
      /** @description Resource not found */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorBody'];
        };
      };
      /** @description Conflict */
      409: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorBody'];
        };
      };
      /** @description Internal server error */
      500: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorBody'];
        };
      };
    };
  };
  get_user_sidebar: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        /** @description User id */
        userId: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Sidebar resource */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/vnd.evidence.sidebar+json': components['schemas']['SidebarResource'];
        };
      };
      /** @description Validation error */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorBody'];
        };
      };
      /** @description Resource not found */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorBody'];
        };
      };
      /** @description Conflict */
      409: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorBody'];
        };
      };
      /** @description Internal server error */
      500: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorBody'];
        };
      };
    };
  };
  list_workspaces: {
    parameters: {
      query?: {
        /** @description Page number */
        page?: number;
        /** @description Page size */
        pageSize?: number;
      };
      header?: never;
      path: {
        /** @description User id */
        userId: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Workspace collection */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/vnd.evidence.workspaces+json': components['schemas']['WorkspaceCollectionResource'];
        };
      };
      /** @description Validation error */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorBody'];
        };
      };
      /** @description Resource not found */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorBody'];
        };
      };
      /** @description Conflict */
      409: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorBody'];
        };
      };
      /** @description Internal server error */
      500: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorBody'];
        };
      };
    };
  };
  create_workspace: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        /** @description User id */
        userId: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['WorkspaceInput'];
      };
    };
    responses: {
      /** @description Created workspace */
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/vnd.evidence.workspaces+json': components['schemas']['WorkspaceResource'];
        };
      };
      /** @description Validation error */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorBody'];
        };
      };
      /** @description Resource not found */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorBody'];
        };
      };
      /** @description Conflict */
      409: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorBody'];
        };
      };
      /** @description Internal server error */
      500: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorBody'];
        };
      };
    };
  };
  get_workspace: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        userId: string;
        workspaceId: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Workspace resource */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/vnd.evidence.workspace+json': components['schemas']['WorkspaceResource'];
        };
      };
      /** @description Validation error */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorBody'];
        };
      };
      /** @description Resource not found */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorBody'];
        };
      };
      /** @description Conflict */
      409: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorBody'];
        };
      };
      /** @description Internal server error */
      500: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorBody'];
        };
      };
    };
  };
  update_workspace: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        userId: string;
        workspaceId: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['WorkspaceInput'];
      };
    };
    responses: {
      /** @description Updated workspace */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/vnd.evidence.workspace+json': components['schemas']['WorkspaceResource'];
        };
      };
      /** @description Validation error */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorBody'];
        };
      };
      /** @description Resource not found */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorBody'];
        };
      };
      /** @description Conflict */
      409: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorBody'];
        };
      };
      /** @description Internal server error */
      500: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorBody'];
        };
      };
    };
  };
  delete_workspace: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        userId: string;
        workspaceId: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Workspace soft-deleted */
      204: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Validation error */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorBody'];
        };
      };
      /** @description Resource not found */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorBody'];
        };
      };
      /** @description Conflict */
      409: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorBody'];
        };
      };
      /** @description Internal server error */
      500: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorBody'];
        };
      };
    };
  };
  list_workspace_members: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        userId: string;
        workspaceId: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Workspace member collection */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/vnd.evidence.members+json': components['schemas']['MemberCollectionResource'];
        };
      };
      /** @description Validation error */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorBody'];
        };
      };
      /** @description Resource not found */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorBody'];
        };
      };
      /** @description Conflict */
      409: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorBody'];
        };
      };
      /** @description Internal server error */
      500: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorBody'];
        };
      };
    };
  };
  add_workspace_member: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        userId: string;
        workspaceId: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['AddMemberInput'];
      };
    };
    responses: {
      /** @description Added workspace member */
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/vnd.evidence.members+json': components['schemas']['MemberResource'];
        };
      };
      /** @description Validation error */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorBody'];
        };
      };
      /** @description Resource not found */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorBody'];
        };
      };
      /** @description Conflict */
      409: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorBody'];
        };
      };
      /** @description Internal server error */
      500: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorBody'];
        };
      };
    };
  };
  get_workspace_member: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        userId: string;
        workspaceId: string;
        memberId: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Workspace member resource */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/vnd.evidence.member+json': components['schemas']['MemberResource'];
        };
      };
      /** @description Validation error */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorBody'];
        };
      };
      /** @description Resource not found */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorBody'];
        };
      };
      /** @description Conflict */
      409: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorBody'];
        };
      };
      /** @description Internal server error */
      500: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorBody'];
        };
      };
    };
  };
  list_diagrams: {
    parameters: {
      query?: {
        page?: number;
        pageSize?: number;
      };
      header?: never;
      path: {
        workspaceId: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Diagram collection */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/vnd.evidence.diagrams+json': components['schemas']['DiagramCollectionResource'];
        };
      };
      /** @description Validation error */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorBody'];
        };
      };
      /** @description Resource not found */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorBody'];
        };
      };
      /** @description Conflict */
      409: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorBody'];
        };
      };
      /** @description Internal server error */
      500: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorBody'];
        };
      };
    };
  };
  create_diagram: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        workspaceId: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['CreateDiagramInput'];
      };
    };
    responses: {
      /** @description Created diagram */
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/vnd.evidence.diagrams+json': components['schemas']['DiagramResource'];
        };
      };
      /** @description Validation error */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorBody'];
        };
      };
      /** @description Resource not found */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorBody'];
        };
      };
      /** @description Conflict */
      409: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorBody'];
        };
      };
      /** @description Internal server error */
      500: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorBody'];
        };
      };
    };
  };
  get_diagram: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        workspaceId: string;
        diagramId: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Diagram resource */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/vnd.evidence.diagram+json': components['schemas']['DiagramResource'];
        };
      };
      /** @description Validation error */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorBody'];
        };
      };
      /** @description Resource not found */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorBody'];
        };
      };
      /** @description Conflict */
      409: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorBody'];
        };
      };
      /** @description Internal server error */
      500: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorBody'];
        };
      };
    };
  };
  update_diagram: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        workspaceId: string;
        diagramId: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['UpdateDiagramInput'];
      };
    };
    responses: {
      /** @description Updated diagram */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/vnd.evidence.diagram+json': components['schemas']['DiagramResource'];
        };
      };
      /** @description Validation error */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorBody'];
        };
      };
      /** @description Resource not found */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorBody'];
        };
      };
      /** @description Conflict */
      409: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorBody'];
        };
      };
      /** @description Internal server error */
      500: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorBody'];
        };
      };
    };
  };
  delete_diagram: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        workspaceId: string;
        diagramId: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Diagram delete result */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/vnd.evidence.diagram+json': components['schemas']['DeletedResult'];
        };
      };
      /** @description Validation error */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorBody'];
        };
      };
      /** @description Resource not found */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorBody'];
        };
      };
      /** @description Conflict */
      409: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorBody'];
        };
      };
      /** @description Internal server error */
      500: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorBody'];
        };
      };
    };
  };
  list_diagram_nodes: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        workspaceId: string;
        diagramId: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Diagram node collection */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/vnd.evidence.nodes+json': components['schemas']['NodeCollectionResource'];
        };
      };
      /** @description Validation error */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorBody'];
        };
      };
      /** @description Resource not found */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorBody'];
        };
      };
      /** @description Conflict */
      409: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorBody'];
        };
      };
      /** @description Internal server error */
      500: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorBody'];
        };
      };
    };
  };
  create_diagram_node: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        workspaceId: string;
        diagramId: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['NodeInput'];
      };
    };
    responses: {
      /** @description Created diagram node */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/vnd.evidence.nodes+json': components['schemas']['NodeResource'];
        };
      };
      /** @description Validation error */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorBody'];
        };
      };
      /** @description Resource not found */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorBody'];
        };
      };
      /** @description Conflict */
      409: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorBody'];
        };
      };
      /** @description Internal server error */
      500: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorBody'];
        };
      };
    };
  };
  get_diagram_node: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        workspaceId: string;
        diagramId: string;
        nodeId: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Diagram node resource */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/vnd.evidence.node+json': components['schemas']['NodeResource'];
        };
      };
      /** @description Validation error */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorBody'];
        };
      };
      /** @description Resource not found */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorBody'];
        };
      };
      /** @description Conflict */
      409: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorBody'];
        };
      };
      /** @description Internal server error */
      500: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorBody'];
        };
      };
    };
  };
  update_diagram_node: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        workspaceId: string;
        diagramId: string;
        nodeId: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['NodeInput'];
      };
    };
    responses: {
      /** @description Updated diagram node */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/vnd.evidence.node+json': components['schemas']['NodeResource'];
        };
      };
      /** @description Validation error */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorBody'];
        };
      };
      /** @description Resource not found */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorBody'];
        };
      };
      /** @description Conflict */
      409: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorBody'];
        };
      };
      /** @description Internal server error */
      500: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorBody'];
        };
      };
    };
  };
  delete_diagram_node: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        workspaceId: string;
        diagramId: string;
        nodeId: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Diagram node delete result */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/vnd.evidence.node+json': components['schemas']['DeletedResult'];
        };
      };
      /** @description Validation error */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorBody'];
        };
      };
      /** @description Resource not found */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorBody'];
        };
      };
      /** @description Conflict */
      409: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorBody'];
        };
      };
      /** @description Internal server error */
      500: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorBody'];
        };
      };
    };
  };
  list_diagram_edges: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        workspaceId: string;
        diagramId: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Diagram edge collection */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/vnd.evidence.edges+json': components['schemas']['EdgeCollectionResource'];
        };
      };
      /** @description Validation error */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorBody'];
        };
      };
      /** @description Resource not found */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorBody'];
        };
      };
      /** @description Conflict */
      409: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorBody'];
        };
      };
      /** @description Internal server error */
      500: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorBody'];
        };
      };
    };
  };
  create_diagram_edge: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        workspaceId: string;
        diagramId: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['EdgeInput'];
      };
    };
    responses: {
      /** @description Created diagram edge */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/vnd.evidence.edges+json': components['schemas']['EdgeResource'];
        };
      };
      /** @description Validation error */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorBody'];
        };
      };
      /** @description Resource not found */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorBody'];
        };
      };
      /** @description Conflict */
      409: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorBody'];
        };
      };
      /** @description Internal server error */
      500: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorBody'];
        };
      };
    };
  };
  get_diagram_edge: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        workspaceId: string;
        diagramId: string;
        edgeId: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Diagram edge resource */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/vnd.evidence.edge+json': components['schemas']['EdgeResource'];
        };
      };
      /** @description Validation error */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorBody'];
        };
      };
      /** @description Resource not found */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorBody'];
        };
      };
      /** @description Conflict */
      409: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorBody'];
        };
      };
      /** @description Internal server error */
      500: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorBody'];
        };
      };
    };
  };
  update_diagram_edge: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        workspaceId: string;
        diagramId: string;
        edgeId: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['EdgeInput'];
      };
    };
    responses: {
      /** @description Updated diagram edge */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/vnd.evidence.edge+json': components['schemas']['EdgeResource'];
        };
      };
      /** @description Validation error */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorBody'];
        };
      };
      /** @description Resource not found */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorBody'];
        };
      };
      /** @description Conflict */
      409: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorBody'];
        };
      };
      /** @description Internal server error */
      500: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorBody'];
        };
      };
    };
  };
  delete_diagram_edge: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        workspaceId: string;
        diagramId: string;
        edgeId: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Diagram edge delete result */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/vnd.evidence.edge+json': components['schemas']['DeletedResult'];
        };
      };
      /** @description Validation error */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorBody'];
        };
      };
      /** @description Resource not found */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorBody'];
        };
      };
      /** @description Conflict */
      409: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorBody'];
        };
      };
      /** @description Internal server error */
      500: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorBody'];
        };
      };
    };
  };
  list_diagram_versions: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        workspaceId: string;
        diagramId: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Diagram version collection */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/vnd.evidence.diagram-versions+json': components['schemas']['DiagramVersionCollectionResource'];
        };
      };
      /** @description Validation error */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorBody'];
        };
      };
      /** @description Resource not found */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorBody'];
        };
      };
      /** @description Conflict */
      409: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorBody'];
        };
      };
      /** @description Internal server error */
      500: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorBody'];
        };
      };
    };
  };
  create_diagram_version: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        workspaceId: string;
        diagramId: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Created diagram version */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/vnd.evidence.diagram-versions+json': components['schemas']['DiagramVersionResource'];
        };
      };
      /** @description Validation error */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorBody'];
        };
      };
      /** @description Resource not found */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorBody'];
        };
      };
      /** @description Conflict */
      409: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorBody'];
        };
      };
      /** @description Internal server error */
      500: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorBody'];
        };
      };
    };
  };
  get_diagram_for_commit_draft: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        workspaceId: string;
        diagramId: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Diagram resource */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/vnd.evidence.diagram+json': components['schemas']['DiagramResource'];
        };
      };
      /** @description Validation error */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorBody'];
        };
      };
      /** @description Resource not found */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorBody'];
        };
      };
      /** @description Conflict */
      409: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorBody'];
        };
      };
      /** @description Internal server error */
      500: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorBody'];
        };
      };
    };
  };
  commit_diagram_draft: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        workspaceId: string;
        diagramId: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['CommitDraftInput'];
      };
    };
    responses: {
      /** @description Draft commit result */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/vnd.evidence.diagram+json': components['schemas']['CommitResult'];
        };
      };
      /** @description Validation error */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorBody'];
        };
      };
      /** @description Resource not found */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorBody'];
        };
      };
      /** @description Conflict */
      409: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorBody'];
        };
      };
      /** @description Internal server error */
      500: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorBody'];
        };
      };
    };
  };
  get_diagram_for_publish: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        workspaceId: string;
        diagramId: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Diagram resource */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/vnd.evidence.diagram+json': components['schemas']['DiagramResource'];
        };
      };
      /** @description Validation error */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorBody'];
        };
      };
      /** @description Resource not found */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorBody'];
        };
      };
      /** @description Conflict */
      409: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorBody'];
        };
      };
      /** @description Internal server error */
      500: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorBody'];
        };
      };
    };
  };
  publish_diagram: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        workspaceId: string;
        diagramId: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Publish result */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/vnd.evidence.diagram+json': components['schemas']['PublishResult'];
        };
      };
      /** @description Validation error */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorBody'];
        };
      };
      /** @description Resource not found */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorBody'];
        };
      };
      /** @description Conflict */
      409: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorBody'];
        };
      };
      /** @description Internal server error */
      500: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorBody'];
        };
      };
    };
  };
  get_diagram_for_propose_model: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        workspaceId: string;
        diagramId: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Diagram resource */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/vnd.evidence.diagram+json': components['schemas']['DiagramResource'];
        };
      };
      /** @description Validation error */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorBody'];
        };
      };
      /** @description Resource not found */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorBody'];
        };
      };
      /** @description Conflict */
      409: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorBody'];
        };
      };
      /** @description Internal server error */
      500: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorBody'];
        };
      };
    };
  };
  propose_diagram_model: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        workspaceId: string;
        diagramId: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['ProposeModelInput'];
      };
    };
    responses: {
      /** @description Server-sent modeling proposal stream */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'text/event-stream': string;
        };
      };
      /** @description Validation error */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorBody'];
        };
      };
      /** @description Resource not found */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorBody'];
        };
      };
      /** @description Conflict */
      409: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorBody'];
        };
      };
      /** @description Internal server error */
      500: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorBody'];
        };
      };
    };
  };
  list_logical_entities: {
    parameters: {
      query?: {
        page?: number;
        pageSize?: number;
      };
      header?: never;
      path: {
        workspaceId: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Logical entity collection */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/vnd.evidence.logical-entities+json': components['schemas']['LogicalEntityCollectionResource'];
        };
      };
      /** @description Validation error */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorBody'];
        };
      };
      /** @description Resource not found */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorBody'];
        };
      };
      /** @description Conflict */
      409: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorBody'];
        };
      };
      /** @description Internal server error */
      500: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorBody'];
        };
      };
    };
  };
  create_logical_entity: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        workspaceId: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['CreateLogicalEntityInput'];
      };
    };
    responses: {
      /** @description Created logical entity */
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/vnd.evidence.logical-entities+json': components['schemas']['LogicalEntityResource'];
        };
      };
      /** @description Validation error */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorBody'];
        };
      };
      /** @description Resource not found */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorBody'];
        };
      };
      /** @description Conflict */
      409: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorBody'];
        };
      };
      /** @description Internal server error */
      500: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorBody'];
        };
      };
    };
  };
  get_logical_entity: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        workspaceId: string;
        entityId: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Logical entity resource */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/vnd.evidence.logical-entity+json': components['schemas']['LogicalEntityResource'];
        };
      };
      /** @description Validation error */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorBody'];
        };
      };
      /** @description Resource not found */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorBody'];
        };
      };
      /** @description Conflict */
      409: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorBody'];
        };
      };
      /** @description Internal server error */
      500: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorBody'];
        };
      };
    };
  };
  update_logical_entity: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        workspaceId: string;
        entityId: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['UpdateLogicalEntityInput'];
      };
    };
    responses: {
      /** @description Updated logical entity */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/vnd.evidence.logical-entity+json': components['schemas']['LogicalEntityResource'];
        };
      };
      /** @description Validation error */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorBody'];
        };
      };
      /** @description Resource not found */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorBody'];
        };
      };
      /** @description Conflict */
      409: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorBody'];
        };
      };
      /** @description Internal server error */
      500: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorBody'];
        };
      };
    };
  };
  delete_logical_entity: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        workspaceId: string;
        entityId: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Logical entity delete result */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/vnd.evidence.logical-entity+json': components['schemas']['DeletedResult'];
        };
      };
      /** @description Validation error */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorBody'];
        };
      };
      /** @description Resource not found */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorBody'];
        };
      };
      /** @description Conflict */
      409: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorBody'];
        };
      };
      /** @description Internal server error */
      500: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorBody'];
        };
      };
    };
  };
}
