/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  '/api': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations['get_root'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/health': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations['get_health'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/users/{userId}': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations['get_user'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/users/{userId}/sidebar': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations['get_user_sidebar'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/users/{userId}/memberships': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations['list_user_memberships'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/workspaces': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post: operations['create_workspace'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/workspaces/{workspaceId}': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations['get_workspace'];
    put: operations['update_workspace'];
    post?: never;
    delete: operations['delete_workspace'];
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/workspaces/{workspaceId}/inbox-items': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations['list_inbox_items'];
    put?: never;
    post: operations['capture_inbox_item'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/workspaces/{workspaceId}/inbox-items/{itemId}': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations['get_inbox_item'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch: operations['change_inbox_item_status'];
    trace?: never;
  };
  '/api/workspaces/{workspaceId}/inbox-items/{itemId}/revisions': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations['list_inbox_revisions'];
    put?: never;
    post: operations['update_inbox_source'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/workspaces/{workspaceId}/inbox-items/{itemId}/revisions/{revisionId}': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations['get_inbox_revision'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/workspaces/{workspaceId}/members': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations['list_workspace_members'];
    put?: never;
    post: operations['add_workspace_member'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/workspaces/{workspaceId}/members/{memberId}': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations['get_workspace_member'];
    put?: never;
    post?: never;
    delete: operations['remove_workspace_member'];
    options?: never;
    head?: never;
    patch: operations['update_workspace_member'];
    trace?: never;
  };
  '/api/workspaces/{workspaceId}/diagram': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations['get_diagram'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/workspaces/{workspaceId}/diagram/nodes': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations['list_diagram_nodes'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/workspaces/{workspaceId}/diagram/nodes/{nodeId}': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations['get_diagram_node'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/workspaces/{workspaceId}/diagram/edges': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations['list_diagram_edges'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/workspaces/{workspaceId}/diagram/edges/{edgeId}': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations['get_diagram_edge'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/workspaces/{workspaceId}/diagram/propose-model': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations['get_diagram_for_propose_model'];
    put?: never;
    post: operations['propose_diagram_model'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/workspaces/{workspaceId}/logical-entities': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations['list_logical_entities'];
    put?: never;
    post: operations['create_logical_entity'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/workspaces/{workspaceId}/logical-entities/{entityId}': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations['get_logical_entity'];
    put: operations['update_logical_entity'];
    post?: never;
    delete: operations['delete_logical_entity'];
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/workspaces/{workspaceId}/logical-relationships': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations['list_logical_relationships'];
    put?: never;
    post: operations['create_logical_relationship'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/workspaces/{workspaceId}/logical-relationships/{relationshipId}': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations['get_logical_relationship'];
    put: operations['update_logical_relationship'];
    post?: never;
    delete: operations['delete_logical_relationship'];
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
}
export type webhooks = Record<string, never>;
export interface components {
  schemas: {
    AddMemberInput: {
      role?: string | null;
      user: components['schemas']['RefModel'];
    };
    UpdateMemberInput: {
      role: string;
    };
    BTreeMap: {
      [key: string]: {
        href: string;
      };
    };
    CreateLogicalEntityInput: {
      content?: string;
      label?: string | null;
      name: string;
      subType?: string | null;
      type: components['schemas']['LogicalEntityType'];
    };
    CreateLogicalRelationshipInput: {
      label?: string | null;
      source: components['schemas']['RefModel'];
      target: components['schemas']['RefModel'];
    };
    DeletedResult: {
      deleted: boolean;
    };
    DiagramCollectionEmbedded: {
      diagrams: components['schemas']['DiagramResource'][];
    };
    DiagramCollectionResource: {
      _embedded: components['schemas']['DiagramCollectionEmbedded'];
      _links: components['schemas']['BTreeMap'];
      _templates: components['schemas']['BTreeMap'];
      page: components['schemas']['PageModel'];
    };
    DiagramResource: {
      _links: components['schemas']['BTreeMap'];
      _templates: components['schemas']['BTreeMap'];
      createdAt: string;
      id: string;
      title: string;
      updatedAt: string;
      viewport: components['schemas']['Viewport'];
    };
    EdgeCollectionEmbedded: {
      edges: components['schemas']['EdgeResource'][];
    };
    EdgeCollectionResource: {
      _embedded: components['schemas']['EdgeCollectionEmbedded'];
      _links: components['schemas']['BTreeMap'];
    };
    EdgeResource: {
      _links: components['schemas']['BTreeMap'];
      animated: boolean;
      createdAt: string;
      data: {
        [key: string]: unknown;
      };
      hidden: boolean;
      id: string;
      /** Format: double */
      interactionWidth?: number | null;
      kind?: string | null;
      logicalRelationship?: null | components['schemas']['RefModel'];
      markerEnd?: {
        [key: string]: unknown;
      } | null;
      markerStart?: {
        [key: string]: unknown;
      } | null;
      pathOptions: {
        [key: string]: unknown;
      };
      source: components['schemas']['RefModel'];
      sourceHandle?: string | null;
      style: {
        [key: string]: unknown;
      };
      target: components['schemas']['RefModel'];
      targetHandle?: string | null;
      updatedAt: string;
    };
    ErrorBody: {
      error: string;
    };
    HealthResource: {
      _links: components['schemas']['BTreeMap'];
      service: string;
      status: string;
    };
    Link: {
      href: string;
    };
    LinkedRefModel: {
      _links: components['schemas']['BTreeMap'];
      id: string;
    };
    InboxItemCollectionEmbedded: {
      inboxItems: components['schemas']['InboxItemResource'][];
    };
    InboxItemCollectionResource: {
      _embedded: components['schemas']['InboxItemCollectionEmbedded'];
      _links: components['schemas']['BTreeMap'];
      page: components['schemas']['PageModel'];
    };
    InboxItemResource: {
      _links: components['schemas']['BTreeMap'];
      id: string;
      sourceKind: string;
      externalKey: string;
      title: string;
      /** @enum {string} */
      status: 'active' | 'deferred' | 'closed';
      latestRevisionId: string;
      latestRevisionSha256: string;
      /** Format: int32 */
      revisionCount: number;
      /** Format: int32 */
      version: number;
      /** Format: date-time */
      createdAt: string;
      /** Format: date-time */
      updatedAt: string;
    };
    InboxItemStatusInput: {
      /** @enum {string} */
      status: 'active' | 'deferred' | 'closed';
      /** Format: int32 */
      expectedVersion: number;
    };
    InboxRevisionCollectionEmbedded: {
      inboxRevisions: components['schemas']['InboxRevisionResource'][];
    };
    InboxRevisionCollectionResource: {
      _embedded: components['schemas']['InboxRevisionCollectionEmbedded'];
      _links: components['schemas']['BTreeMap'];
      page: components['schemas']['PageModel'];
    };
    InboxSourceUpdateInput: {
      title?: string;
      body?: string;
      /** @enum {string} */
      contentType?: 'text/plain' | 'text/markdown';
      /** Format: uri */
      uri?: string | null;
      providerMetadata?: {
        [key: string]: unknown;
      } | null;
      /** Format: date-time */
      sourceUpdatedAt?: string | null;
      expectedLatestRevisionSha256: string;
    };
    InboxRevisionResource: {
      _links: components['schemas']['BTreeMap'];
      id: string;
      /** Format: int32 */
      revisionNumber: number;
      title: string;
      body: string;
      /** @enum {string} */
      contentType: 'text/plain' | 'text/markdown';
      /** Format: uri */
      uri?: string | null;
      providerMetadata: {
        [key: string]: unknown;
      };
      /** Format: date-time */
      sourceUpdatedAt?: string | null;
      /** Format: date-time */
      capturedAt: string;
      contentSha256: string;
    };
    InboxSourceInput: {
      sourceKind: string;
      externalKey: string;
      title: string;
      body: string;
      /** @enum {string} */
      contentType: 'text/plain' | 'text/markdown';
      /** Format: uri */
      uri?: string | null;
      providerMetadata?: {
        [key: string]: unknown;
      };
      /** Format: date-time */
      sourceUpdatedAt?: string | null;
    };
    LogicalEntityCollectionEmbedded: {
      logicalEntities: components['schemas']['LogicalEntityResource'][];
    };
    LogicalEntityCollectionResource: {
      _embedded: components['schemas']['LogicalEntityCollectionEmbedded'];
      _links: components['schemas']['BTreeMap'];
      page: components['schemas']['PageModel'];
    };
    LogicalEntityResource: {
      _links: components['schemas']['BTreeMap'];
      content: string;
      id: string;
      label?: string | null;
      name: string;
      subType?: string | null;
      type: components['schemas']['LogicalEntityType'];
    };
    /** @enum {string} */
    LogicalEntityType: 'EVIDENCE' | 'PARTICIPANT' | 'ROLE' | 'CONTEXT';
    LogicalRelationshipCollectionEmbedded: {
      logicalRelationships: components['schemas']['LogicalRelationshipResource'][];
    };
    LogicalRelationshipCollectionResource: {
      _embedded: components['schemas']['LogicalRelationshipCollectionEmbedded'];
      _links: components['schemas']['BTreeMap'];
      page: components['schemas']['PageModel'];
    };
    LogicalRelationshipResource: {
      _links: components['schemas']['BTreeMap'];
      id: string;
      label?: string | null;
      source: components['schemas']['RefModel'];
      target: components['schemas']['RefModel'];
    };
    MemberCollectionEmbedded: {
      members: components['schemas']['MemberResource'][];
    };
    MemberCollectionResource: {
      _embedded: components['schemas']['MemberCollectionEmbedded'];
      _links: components['schemas']['BTreeMap'];
      page: components['schemas']['PageModel'];
    };
    MemberResource: {
      _links: components['schemas']['BTreeMap'];
      createdAt: string;
      id: string;
      role: string;
      updatedAt: string;
      user: components['schemas']['LinkedRefModel'];
      workspace: components['schemas']['LinkedRefModel'];
    };
    MembershipCollectionEmbedded: {
      memberships: components['schemas']['MembershipResource'][];
    };
    MembershipCollectionResource: {
      _embedded: components['schemas']['MembershipCollectionEmbedded'];
      _links: components['schemas']['BTreeMap'];
      page: components['schemas']['PageModel'];
    };
    MembershipResource: {
      _links: components['schemas']['BTreeMap'];
      createdAt: string;
      id: string;
      role: string;
      updatedAt: string;
      user: components['schemas']['LinkedRefModel'];
      workspace: components['schemas']['WorkspaceResource'];
    };
    NodeCollectionEmbedded: {
      nodes: components['schemas']['NodeResource'][];
    };
    NodeCollectionResource: {
      _embedded: components['schemas']['NodeCollectionEmbedded'];
      _links: components['schemas']['BTreeMap'];
    };
    NodeEmbedded: {
      'logical-entity': components['schemas']['LogicalEntityResource'];
    };
    NodeResource: {
      _embedded?: null | components['schemas']['NodeEmbedded'];
      _links: components['schemas']['BTreeMap'];
      createdAt: string;
      data: {
        [key: string]: unknown;
      };
      /** Format: int64 */
      height?: number | null;
      id: string;
      kind: string;
      parent?: null | components['schemas']['RefModel'];
      position: components['schemas']['Position'];
      updatedAt: string;
      /** Format: int64 */
      width?: number | null;
    };
    PageModel: {
      /** Format: int32 */
      number: number;
      /** Format: int32 */
      size: number;
      /** Format: int64 */
      totalElements: number;
      /** Format: int64 */
      totalPages: number;
    };
    Position: {
      /** Format: double */
      x: number;
      /** Format: double */
      y: number;
    };
    ProposeModelInput: {
      requirement: string;
    };
    RefModel: {
      id: string;
    };
    RootResource: {
      _links: components['schemas']['BTreeMap'];
    };
    SidebarItem: {
      active?: boolean | null;
      defaultOpen?: boolean | null;
      href: string;
      icon: string;
      key: string;
      label: string;
      path: string;
      rel?: string | null;
      template?: string | null;
      type: string;
    };
    SidebarResource: {
      _links: components['schemas']['BTreeMap'];
      sections: components['schemas']['SidebarSection'][];
    };
    SidebarSection: {
      defaultOpen: boolean;
      items: components['schemas']['SidebarItem'][];
      key: string;
      title: string;
    };
    TemplateProperty: {
      /** Format: int32 */
      minLength?: number | null;
      name: string;
      prompt?: string | null;
      required?: boolean | null;
      type?: string | null;
      value?: string | null;
    };
    UpdateLogicalEntityInput: {
      content?: string | null;
      label?: string | null;
      name?: string | null;
      subType?: string | null;
      type?: null | components['schemas']['LogicalEntityType'];
    };
    UpdateLogicalRelationshipInput: {
      label?: string | null;
      source?: null | components['schemas']['RefModel'];
      target?: null | components['schemas']['RefModel'];
    };
    UserResource: {
      _links: components['schemas']['BTreeMap'];
      email?: string | null;
      id: string;
      name: string;
    };
    Viewport: {
      /** Format: double */
      x: number;
      /** Format: double */
      y: number;
      /** Format: double */
      zoom: number;
    };
    WorkspaceInput: {
      description?: string | null;
      metadata?: {
        [key: string]: string;
      } | null;
      status?: string | null;
      title?: string | null;
    };
    WorkspaceResource: {
      _links: components['schemas']['BTreeMap'];
      createdAt: string;
      description?: string | null;
      id: string;
      metadata: {
        [key: string]: string;
      };
      status: string;
      title: string;
      updatedAt: string;
    };
  };
  responses: never;
  parameters: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
  get_root: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description API root resource */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/vnd.evidence.root+json': components['schemas']['RootResource'];
        };
      };
    };
  };
  get_health: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Health resource */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/vnd.evidence.health+json': components['schemas']['HealthResource'];
        };
      };
    };
  };
  get_user: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        /** @description User id */
        userId: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description User resource */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/vnd.evidence.user+json': components['schemas']['UserResource'];
        };
      };
      /** @description Validation error */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorBody'];
        };
      };
      /** @description Resource not found */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorBody'];
        };
      };
      /** @description Conflict */
      409: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorBody'];
        };
      };
      /** @description Internal server error */
      500: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorBody'];
        };
      };
    };
  };
  get_user_sidebar: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        /** @description User id */
        userId: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Sidebar resource */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/vnd.evidence.sidebar+json': components['schemas']['SidebarResource'];
        };
      };
      /** @description Validation error */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorBody'];
        };
      };
      /** @description Resource not found */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorBody'];
        };
      };
      /** @description Conflict */
      409: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorBody'];
        };
      };
      /** @description Internal server error */
      500: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorBody'];
        };
      };
    };
  };
  list_user_memberships: {
    parameters: {
      query?: {
        /** @description Page number */
        page?: number;
        /** @description Page size */
        pageSize?: number;
      };
      header?: never;
      path: {
        /** @description User id */
        userId: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description User membership collection */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/vnd.evidence.memberships+json': components['schemas']['MembershipCollectionResource'];
        };
      };
      /** @description Validation error */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorBody'];
        };
      };
      /** @description Resource not found */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorBody'];
        };
      };
      /** @description Internal server error */
      500: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorBody'];
        };
      };
    };
  };
  create_workspace: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['WorkspaceInput'];
      };
    };
    responses: {
      /** @description Created workspace */
      201: {
        headers: {
          /** @description Canonical workspace URI */
          Location?: string;
          [name: string]: unknown;
        };
        content: {
          'application/vnd.evidence.workspace+json': components['schemas']['WorkspaceResource'];
        };
      };
      /** @description Validation error */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorBody'];
        };
      };
      /** @description Resource not found */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorBody'];
        };
      };
      /** @description Conflict */
      409: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorBody'];
        };
      };
      /** @description Internal server error */
      500: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorBody'];
        };
      };
    };
  };
  get_workspace: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        workspaceId: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Workspace resource */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/vnd.evidence.workspace+json': components['schemas']['WorkspaceResource'];
        };
      };
      /** @description Resource not found */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorBody'];
        };
      };
      /** @description Internal server error */
      500: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorBody'];
        };
      };
    };
  };
  update_workspace: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        workspaceId: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['WorkspaceInput'];
      };
    };
    responses: {
      /** @description Updated workspace */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/vnd.evidence.workspace+json': components['schemas']['WorkspaceResource'];
        };
      };
      /** @description Validation error */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorBody'];
        };
      };
      /** @description Resource not found */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorBody'];
        };
      };
      /** @description Conflict */
      409: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorBody'];
        };
      };
      /** @description Internal server error */
      500: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorBody'];
        };
      };
    };
  };
  delete_workspace: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        workspaceId: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Workspace soft-deleted */
      204: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Resource not found */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorBody'];
        };
      };
      /** @description Conflict */
      409: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorBody'];
        };
      };
      /** @description Internal server error */
      500: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorBody'];
        };
      };
    };
  };
  list_inbox_items: {
    parameters: {
      query?: {
        page?: number;
        pageSize?: number;
        status?: 'active' | 'deferred' | 'closed';
        sourceKind?: string;
        q?: string;
      };
      header?: never;
      path: {
        workspaceId: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Workspace Inbox item collection */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/vnd.evidence.inbox-items+json': components['schemas']['InboxItemCollectionResource'];
        };
      };
      /** @description Validation error */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorBody'];
        };
      };
      /** @description Workspace not found */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorBody'];
        };
      };
      /** @description Internal server error */
      500: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorBody'];
        };
      };
    };
  };
  capture_inbox_item: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        workspaceId: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['InboxSourceInput'];
      };
    };
    responses: {
      /** @description Captured Inbox item and first immutable revision */
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/vnd.evidence.inbox-item+json': components['schemas']['InboxItemResource'];
        };
      };
      /** @description Validation error */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorBody'];
        };
      };
      /** @description Workspace not found */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorBody'];
        };
      };
      /** @description Inbox source already exists */
      409: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorBody'];
        };
      };
      /** @description Internal server error */
      500: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorBody'];
        };
      };
    };
  };
  get_inbox_item: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        workspaceId: string;
        itemId: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Workspace Inbox item */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/vnd.evidence.inbox-item+json': components['schemas']['InboxItemResource'];
        };
      };
      /** @description Inbox item not found */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorBody'];
        };
      };
      /** @description Internal server error */
      500: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorBody'];
        };
      };
    };
  };
  change_inbox_item_status: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        workspaceId: string;
        itemId: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['InboxItemStatusInput'];
      };
    };
    responses: {
      /** @description Updated Inbox item */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/vnd.evidence.inbox-item+json': components['schemas']['InboxItemResource'];
        };
      };
      /** @description Validation error */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorBody'];
        };
      };
      /** @description Inbox item not found */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorBody'];
        };
      };
      /** @description Inbox item version conflict */
      409: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorBody'];
        };
      };
      /** @description Internal server error */
      500: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorBody'];
        };
      };
    };
  };
  list_inbox_revisions: {
    parameters: {
      query?: {
        page?: number;
        pageSize?: number;
      };
      header?: never;
      path: {
        workspaceId: string;
        itemId: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Inbox source revision collection */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/vnd.evidence.inbox-revisions+json': components['schemas']['InboxRevisionCollectionResource'];
        };
      };
      /** @description Validation error */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorBody'];
        };
      };
      /** @description Inbox item not found */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorBody'];
        };
      };
      /** @description Internal server error */
      500: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorBody'];
        };
      };
    };
  };
  update_inbox_source: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        workspaceId: string;
        itemId: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['InboxSourceUpdateInput'];
      };
    };
    responses: {
      /** @description Updated source snapshot; unchanged content reuses the latest revision */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/vnd.evidence.inbox-revision+json': components['schemas']['InboxRevisionResource'];
        };
      };
      /** @description Validation error */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorBody'];
        };
      };
      /** @description Inbox item not found */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorBody'];
        };
      };
      /** @description Latest Inbox revision changed */
      409: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorBody'];
        };
      };
      /** @description Internal server error */
      500: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorBody'];
        };
      };
    };
  };
  get_inbox_revision: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        workspaceId: string;
        itemId: string;
        revisionId: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Immutable Inbox source revision */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/vnd.evidence.inbox-revision+json': components['schemas']['InboxRevisionResource'];
        };
      };
      /** @description Inbox revision not found */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorBody'];
        };
      };
      /** @description Internal server error */
      500: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorBody'];
        };
      };
    };
  };
  list_workspace_members: {
    parameters: {
      query?: {
        /** @description Page number */
        page?: number;
        /** @description Page size */
        pageSize?: number;
      };
      header?: never;
      path: {
        workspaceId: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Workspace member collection */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/vnd.evidence.members+json': components['schemas']['MemberCollectionResource'];
        };
      };
      /** @description Validation error */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorBody'];
        };
      };
      /** @description Resource not found */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorBody'];
        };
      };
      /** @description Internal server error */
      500: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorBody'];
        };
      };
    };
  };
  add_workspace_member: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        workspaceId: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['AddMemberInput'];
      };
    };
    responses: {
      /** @description Added workspace member */
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/vnd.evidence.member+json': components['schemas']['MemberResource'];
        };
      };
      /** @description Validation error */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorBody'];
        };
      };
      /** @description Resource not found */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorBody'];
        };
      };
      /** @description Conflict */
      409: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorBody'];
        };
      };
      /** @description Internal server error */
      500: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorBody'];
        };
      };
    };
  };
  get_workspace_member: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        workspaceId: string;
        memberId: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Workspace member resource */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/vnd.evidence.member+json': components['schemas']['MemberResource'];
        };
      };
      /** @description Resource not found */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorBody'];
        };
      };
      /** @description Internal server error */
      500: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorBody'];
        };
      };
    };
  };
  remove_workspace_member: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        workspaceId: string;
        memberId: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Removed workspace member */
      204: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Resource not found */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorBody'];
        };
      };
      /** @description Conflict */
      409: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorBody'];
        };
      };
      /** @description Internal server error */
      500: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorBody'];
        };
      };
    };
  };
  update_workspace_member: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        workspaceId: string;
        memberId: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['UpdateMemberInput'];
      };
    };
    responses: {
      /** @description Updated workspace member */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/vnd.evidence.member+json': components['schemas']['MemberResource'];
        };
      };
      /** @description Validation error */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorBody'];
        };
      };
      /** @description Resource not found */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorBody'];
        };
      };
      /** @description Conflict */
      409: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorBody'];
        };
      };
      /** @description Internal server error */
      500: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorBody'];
        };
      };
    };
  };
  get_diagram: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        workspaceId: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Diagram resource */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/vnd.evidence.diagram+json': components['schemas']['DiagramResource'];
        };
      };
      /** @description Validation error */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorBody'];
        };
      };
      /** @description Resource not found */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorBody'];
        };
      };
      /** @description Conflict */
      409: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorBody'];
        };
      };
      /** @description Internal server error */
      500: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorBody'];
        };
      };
    };
  };
  list_diagram_nodes: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        workspaceId: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Diagram node collection */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/vnd.evidence.nodes+json': components['schemas']['NodeCollectionResource'];
        };
      };
      /** @description Validation error */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorBody'];
        };
      };
      /** @description Resource not found */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorBody'];
        };
      };
      /** @description Conflict */
      409: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorBody'];
        };
      };
      /** @description Internal server error */
      500: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorBody'];
        };
      };
    };
  };
  get_diagram_node: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        workspaceId: string;
        nodeId: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Diagram node resource */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/vnd.evidence.node+json': components['schemas']['NodeResource'];
        };
      };
      /** @description Validation error */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorBody'];
        };
      };
      /** @description Resource not found */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorBody'];
        };
      };
      /** @description Conflict */
      409: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorBody'];
        };
      };
      /** @description Internal server error */
      500: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorBody'];
        };
      };
    };
  };
  list_diagram_edges: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        workspaceId: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Diagram edge collection */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/vnd.evidence.edges+json': components['schemas']['EdgeCollectionResource'];
        };
      };
      /** @description Validation error */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorBody'];
        };
      };
      /** @description Resource not found */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorBody'];
        };
      };
      /** @description Conflict */
      409: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorBody'];
        };
      };
      /** @description Internal server error */
      500: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorBody'];
        };
      };
    };
  };
  get_diagram_edge: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        workspaceId: string;
        edgeId: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Diagram edge resource */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/vnd.evidence.edge+json': components['schemas']['EdgeResource'];
        };
      };
      /** @description Validation error */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorBody'];
        };
      };
      /** @description Resource not found */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorBody'];
        };
      };
      /** @description Conflict */
      409: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorBody'];
        };
      };
      /** @description Internal server error */
      500: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorBody'];
        };
      };
    };
  };
  get_diagram_for_propose_model: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        workspaceId: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Diagram resource */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/vnd.evidence.diagram+json': components['schemas']['DiagramResource'];
        };
      };
      /** @description Validation error */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorBody'];
        };
      };
      /** @description Resource not found */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorBody'];
        };
      };
      /** @description Conflict */
      409: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorBody'];
        };
      };
      /** @description Internal server error */
      500: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorBody'];
        };
      };
    };
  };
  propose_diagram_model: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        workspaceId: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['ProposeModelInput'];
      };
    };
    responses: {
      /** @description Server-sent modeling proposal stream */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'text/event-stream': string;
        };
      };
      /** @description Validation error */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorBody'];
        };
      };
      /** @description Resource not found */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorBody'];
        };
      };
      /** @description Conflict */
      409: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorBody'];
        };
      };
      /** @description Internal server error */
      500: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorBody'];
        };
      };
    };
  };
  list_logical_entities: {
    parameters: {
      query?: {
        page?: number;
        pageSize?: number;
      };
      header?: never;
      path: {
        workspaceId: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Logical entity collection */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/vnd.evidence.logical-entities+json': components['schemas']['LogicalEntityCollectionResource'];
        };
      };
      /** @description Validation error */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorBody'];
        };
      };
      /** @description Resource not found */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorBody'];
        };
      };
      /** @description Conflict */
      409: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorBody'];
        };
      };
      /** @description Internal server error */
      500: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorBody'];
        };
      };
    };
  };
  create_logical_entity: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        workspaceId: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['CreateLogicalEntityInput'];
      };
    };
    responses: {
      /** @description Created logical entity */
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/vnd.evidence.logical-entities+json': components['schemas']['LogicalEntityResource'];
        };
      };
      /** @description Validation error */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorBody'];
        };
      };
      /** @description Resource not found */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorBody'];
        };
      };
      /** @description Conflict */
      409: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorBody'];
        };
      };
      /** @description Internal server error */
      500: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorBody'];
        };
      };
    };
  };
  get_logical_entity: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        workspaceId: string;
        entityId: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Logical entity resource */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/vnd.evidence.logical-entity+json': components['schemas']['LogicalEntityResource'];
        };
      };
      /** @description Validation error */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorBody'];
        };
      };
      /** @description Resource not found */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorBody'];
        };
      };
      /** @description Conflict */
      409: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorBody'];
        };
      };
      /** @description Internal server error */
      500: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorBody'];
        };
      };
    };
  };
  update_logical_entity: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        workspaceId: string;
        entityId: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['UpdateLogicalEntityInput'];
      };
    };
    responses: {
      /** @description Updated logical entity */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/vnd.evidence.logical-entity+json': components['schemas']['LogicalEntityResource'];
        };
      };
      /** @description Validation error */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorBody'];
        };
      };
      /** @description Resource not found */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorBody'];
        };
      };
      /** @description Conflict */
      409: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorBody'];
        };
      };
      /** @description Internal server error */
      500: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorBody'];
        };
      };
    };
  };
  delete_logical_entity: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        workspaceId: string;
        entityId: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Logical entity delete result */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/vnd.evidence.logical-entity+json': components['schemas']['DeletedResult'];
        };
      };
      /** @description Validation error */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorBody'];
        };
      };
      /** @description Resource not found */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorBody'];
        };
      };
      /** @description Conflict */
      409: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorBody'];
        };
      };
      /** @description Internal server error */
      500: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorBody'];
        };
      };
    };
  };
  list_logical_relationships: {
    parameters: {
      query?: {
        page?: number;
        pageSize?: number;
      };
      header?: never;
      path: {
        workspaceId: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Logical relationship collection */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/vnd.evidence.logical-relationships+json': components['schemas']['LogicalRelationshipCollectionResource'];
        };
      };
      /** @description Validation error */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorBody'];
        };
      };
      /** @description Resource not found */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorBody'];
        };
      };
      /** @description Conflict */
      409: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorBody'];
        };
      };
      /** @description Internal server error */
      500: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorBody'];
        };
      };
    };
  };
  create_logical_relationship: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        workspaceId: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['CreateLogicalRelationshipInput'];
      };
    };
    responses: {
      /** @description Created logical relationship */
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/vnd.evidence.logical-relationships+json': components['schemas']['LogicalRelationshipResource'];
        };
      };
      /** @description Validation error */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorBody'];
        };
      };
      /** @description Resource not found */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorBody'];
        };
      };
      /** @description Conflict */
      409: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorBody'];
        };
      };
      /** @description Internal server error */
      500: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorBody'];
        };
      };
    };
  };
  get_logical_relationship: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        workspaceId: string;
        relationshipId: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Logical relationship resource */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/vnd.evidence.logical-relationship+json': components['schemas']['LogicalRelationshipResource'];
        };
      };
      /** @description Validation error */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorBody'];
        };
      };
      /** @description Resource not found */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorBody'];
        };
      };
      /** @description Conflict */
      409: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorBody'];
        };
      };
      /** @description Internal server error */
      500: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorBody'];
        };
      };
    };
  };
  update_logical_relationship: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        workspaceId: string;
        relationshipId: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['UpdateLogicalRelationshipInput'];
      };
    };
    responses: {
      /** @description Updated logical relationship */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/vnd.evidence.logical-relationship+json': components['schemas']['LogicalRelationshipResource'];
        };
      };
      /** @description Validation error */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorBody'];
        };
      };
      /** @description Resource not found */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorBody'];
        };
      };
      /** @description Conflict */
      409: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorBody'];
        };
      };
      /** @description Internal server error */
      500: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorBody'];
        };
      };
    };
  };
  delete_logical_relationship: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        workspaceId: string;
        relationshipId: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Logical relationship delete result */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/vnd.evidence.logical-relationship+json': components['schemas']['DeletedResult'];
        };
      };
      /** @description Validation error */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorBody'];
        };
      };
      /** @description Resource not found */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorBody'];
        };
      };
      /** @description Conflict */
      409: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorBody'];
        };
      };
      /** @description Internal server error */
      500: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorBody'];
        };
      };
    };
  };
}
